[pytest]
testpaths = tests
python_files = test_*.py
pythonpath = .
addopts = -ra -q --cov=src --cov-report=term-missing --cov-report=xml

filterwarnings =
    ignore:.*Type google._upb._message.MessageMapContainer uses PyType_Spec.*:DeprecationWarning
    ignore:.*Type google._upb._message.ScalarMapContainer uses PyType_Spec.*:DeprecationWarning
    ignore:.*SymbolDatabase.GetPrototype\(\) is deprecated.*:UserWarning
